#!/bin/python

with open("example.cimg", "wb") as file:
    file.write(b"<@Nr")
    file.write((1).to_bytes(1, "little"))
    file.write((44).to_bytes(2, "little"))
    file.write((24).to_bytes(2, "little"))
    file.write(b"M" * (44*24))
